# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hId7zQITtPhNHVbxyCwO4fCnFd0PFReb
"""

import streamlit as st
import pandas as pd
import joblib
import os
import requests

# 🔹 Set Google Drive path (Modify if necessary)
#drive_path = "/content/"


# 🔹 Load the trained model and vectorizer
@st.cache_resource
def load_model():
    model_path = os.path.join("disease_model.pkl")
    vectorizer_path = os.path.join("tfidf_vectorizer.pkl")

    if not os.path.exists(model_path) or not os.path.exists(vectorizer_path):
        st.error("🚨 Model or vectorizer not found! Please train and save them first.")
        return None, None

    clf = joblib.load(model_path,mmap_mode="r")
    vectorizer = joblib.load(vectorizer_path)
    return clf, vectorizer

# 🔹 Load Model & Vectorizer
clf, vectorizer_tfidf = load_model()


# 🔹 Hugging Face API for Treatment Recommendations
HF_API_KEY = st.secrets["HF_API_KEY"]

def get_treatment_recommendation(disease):
    """Query Hugging Face API for AI-powered treatment recommendations."""
    API_URL = "https://api-inference.huggingface.co/models/google/flan-t5-large"
    headers = {"Authorization": f"Bearer {HF_API_KEY}"}
    payload = {"inputs": f"What is the recommended treatment for {disease}?"}

    response = requests.post(API_URL, headers=headers, json=payload)

    if response.status_code == 200:
        result = response.json()
        if result and isinstance(result, list) and "generated_text" in result[0]:
            return result[0]["generated_text"]
        else:
            return "⚠️ No generated text in response."
    else:
        return f"⚠️ Error: {response.status_code} - {response.text}"

# 🔹 Streamlit UI
st.title("🩺 Disease Prediction & Treatment Recommendations")
st.write("Select your symptoms below to get a predicted disease and treatment suggestion.")

# 🔹 Load Symptoms Dataset
@st.cache_data
def load_symptom_data():
    data_path = os.path.join("processed_diseases-priority.csv")  # Ensure correct file path
    df = pd.read_csv(data_path)
    return df

df = load_symptom_data()

# 🔹 Extract Unique Symptoms
all_symptoms = set()
for symptoms in df["Symptoms"].astype(str).fillna(""):
    all_symptoms.update(symptoms.split(", "))

# 🔹 User Input: Multi-select Symptoms
selected_symptoms = st.multiselect("🩺 Select Symptoms:", sorted(all_symptoms))

if st.button("🔍 Predict Disease & Get Treatment"):
    if selected_symptoms:
        # 🔹 Format symptoms into a single input string
        symptoms_input = ", ".join(selected_symptoms)


        # 🔹 Predict disease using TF-IDF + Random Forest
        input_vector = vectorizer_tfidf.transform([symptoms_input])
        predicted_disease = clf.predict(input_vector)[0]

        # 🔹 Get AI-generated treatment recommendation
        treatment_recommendation = get_treatment_recommendation(predicted_disease)

        # 🔹 Display results
        st.success(f"🩺 **Predicted Disease:** {predicted_disease}")
        st.info(f"💊 **AI-Recommended Treatment:** {treatment_recommendation}")
    else:
        st.warning("⚠️ Please select at least one symptom!")